-- Generated from generator/demo_specs/aws-vietnam-renewable-grid.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-renewable-grid
-- This is the schema that is actually deployed for VIETNAM_RENEWABLE_GRID.

-- Alerts fire on the bottom tail of RE Penetration
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_RE_PENETRATION) AS T
  FROM RAW.LOAD_READINGS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_RE_PENETRATION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_RE_PENETRATION), 2) AS AVG_RE_PENETRATION,
  ROUND(AVG(f.KPI_GRID_FREQUENCY), 2) AS AVG_GRID_FREQUENCY,
  ROUND(AVG(f.KPI_PEAK_RE_TODAY), 2) AS AVG_PEAK_RE_TODAY,
  ROUND(AVG(f.KPI_RAMP_RATE), 2) AS AVG_RAMP_RATE,
  ROUND(AVG(f.KPI_STORAGE_ONLINE), 2) AS AVG_STORAGE_ONLINE
FROM RAW.LOAD_READINGS f
JOIN RAW.SUBSTATIONS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_RE_PENETRATION), 2) AS AVG_RE_PENETRATION,
  ROUND(AVG(f.KPI_GRID_FREQUENCY), 2) AS AVG_GRID_FREQUENCY,
  ROUND(AVG(f.KPI_PEAK_RE_TODAY), 2) AS AVG_PEAK_RE_TODAY,
  ROUND(AVG(f.KPI_RAMP_RATE), 2) AS AVG_RAMP_RATE,
  ROUND(AVG(f.KPI_STORAGE_ONLINE), 2) AS AVG_STORAGE_ONLINE
FROM RAW.LOAD_READINGS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_RE_PENETRATION) AS KPI_RE_PENETRATION, AVG(KPI_GRID_FREQUENCY) AS KPI_GRID_FREQUENCY, AVG(KPI_PEAK_RE_TODAY) AS KPI_PEAK_RE_TODAY, AVG(KPI_RAMP_RATE) AS KPI_RAMP_RATE, AVG(KPI_STORAGE_ONLINE) AS KPI_STORAGE_ONLINE FROM RAW.LOAD_READINGS),
     en AS (SELECT SUM(KPI_CURTAILMENT_MTD) AS KPI_CURTAILMENT_MTD, SUM(KPI_SUBSTATIONS) AS KPI_SUBSTATIONS FROM RAW.SUBSTATIONS)
  SELECT 1 AS SORT_ORDER, 'RE Penetration' AS TITLE, KPI_RE_PENETRATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RE_PENETRATION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Grid Frequency' AS TITLE, KPI_GRID_FREQUENCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_GRID_FREQUENCY), 2) AS DECIMAL(38,2))) || ' ' || 'Hz' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Curtailment (MTD)' AS TITLE, KPI_CURTAILMENT_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CURTAILMENT_MTD)) AS DECIMAL(38,0))) || ' ' || 'GWh' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Substations' AS TITLE, KPI_SUBSTATIONS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SUBSTATIONS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Peak RE (Today)' AS TITLE, KPI_PEAK_RE_TODAY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PEAK_RE_TODAY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Ramp Rate' AS TITLE, KPI_RAMP_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RAMP_RATE), 1) AS DECIMAL(38,1))) || ' ' || 'GW/hr' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Storage Online' AS TITLE, KPI_STORAGE_ONLINE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_STORAGE_ONLINE)) AS DECIMAL(38,0))) || ' ' || 'MWh' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
