-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Grid Integration
-- ============================================================================
USE DATABASE GRID_INTEGRATION;
USE SCHEMA ML;

-- ML.FORECAST: GRID_INTEGRATION_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.GRID_INTEGRATION_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FORECAST_INPUT'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.GRID_INTEGRATION_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.GRID_INTEGRATION_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: GRID_INTEGRATION_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.GRID_INTEGRATION_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.GRID_INTEGRATION_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.GRID_INTEGRATION_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'), SERIES_COLNAME => 'ENTITY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

